# Mosquitto config for Lego Flow interoperability tests

listener 1883

allow_anonymous true

log_type all

# Enable persistence (optional)
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
