#!/usr/bin/env python3
"""
Generate LAYOUTS.md from message/*.json (apache/kafka 3.6.1, verbatim artifacts).

LAYOUTS.md is a GENERATED file — edit the JSON artifacts, then run:
    python3 messaging/kafka/doc/spec/dump_layouts.py

The dump is lossless w.r.t. the schema: for every version 0..max it lists the
exact body fields in wire order, with per-version gates, nullability, map keys
and KIP-482 tagged-field markers. A field that was *removed* in a later
version disappears from that version's list (the classic failure mode of
hand-maintained layout tables).

Spec file format (apache/kafka message/*.json, 3.6.1):
  top level: apiKey, type, listeners, name, validVersions ("0-N"),
             flexibleVersions ("N+" | ""), fields
  field:     name, type, field, versions ("N" | "N+" | "N-M"),
             nullableVersions, mapKey, taggedVersions, tag,
             fields (inline definition of a named/array component type)
"""
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
MSG = os.path.join(BASE, "message")


def load(name):
    with open(os.path.join(MSG, name)) as f:
        text = re.sub(r"^ *//.*$", "", f.read(), flags=re.MULTILINE)
    return json.loads(text)


def parse_spec(spec):
    """'N' -> (N,N); 'N+' -> (N,None); 'N-M' -> (N,M). None -> None (no gate)."""
    if spec is None:
        return None
    spec = spec.strip()
    if spec.endswith("+"):
        return (int(spec[:-1]), None)
    if "-" in spec:
        lo, hi = spec.split("-")
        return (int(lo), int(hi))
    n = int(spec)
    return (n, n)


def covers(gate, version):
    """True when version gate applies to `version`. None gate = always."""
    if gate is None:
        return True
    lo, hi = parse_spec(gate)
    if lo is None:
        return True
    if version < lo:
        return False
    if hi is not None and version > hi:
        return False
    return True


def field_present(f, version):
    return covers(f.get("versions"), version)


def api_max_version(d):
    lo, hi = parse_spec(d.get("validVersions", "0"))
    return hi if hi is not None else lo


def field_signature(f, version):
    """One layout line for field `f` at `version`: name type [null] [key] [tag#N]."""
    parts = [f["name"], f["type"]]
    if f.get("mapKey"):
        parts.append("key")
    if f.get("nullableVersions") and covers(f["nullableVersions"], version):
        parts.append("null")
    if f.get("taggedVersions") and covers(f["taggedVersions"], version):
        parts.append(f"tag#{f['tag']}")
    return " ".join(parts)


def dump_fields(fields, version, indent, lines):
    for f in fields:
        if not field_present(f, version):
            continue
        lines.append(indent + field_signature(f, version))
        sub = f.get("fields")
        if sub:
            # Named / array component type — inline definition, recurse.
            dump_fields(sub, version, indent + "    ", lines)


def dump_one(d):
    kind = "Request" if d["name"].endswith("Request") else "Response"
    disp = d["name"][: -len(kind)]
    maxv = api_max_version(d)
    flex = d.get("flexibleVersions") or ""
    header = f"## {disp} {kind} — key {d['apiKey']}, v0..v{maxv}"
    if flex:
        header += f", flexible {flex}"
    out = [header + "\n"]
    for v in range(maxv + 1):
        out.append(f"### {kind} v{v}")
        body = []
        dump_fields(d["fields"], v, "  ", body)
        out.extend(body if body else ["  (no body fields)"])
        out.append("")
    return "\n".join(out)


def main():
    pairs = []
    for f in sorted(os.listdir(MSG)):
        if f.endswith("Request.json"):
            base = os.path.join(MSG, f[: -len("Request.json")] + "Response.json")
            if os.path.exists(base):
                pairs.append((f, base))
    pairs.sort(key=lambda p: load(p[0])["apiKey"])
    out = [
        "# Kafka wire layouts per version — generated from message/*.json",
        "",
        "Source: apache/kafka 3.6.1, `clients/src/main/resources/common/message/*.json`",
        "(verbatim artifacts in this directory). **Generated by `dump_layouts.py` —",
        "do not edit by hand.**",
        "",
        "Conventions: `[]Name` = array (int32 count + Name*, Name's fields listed",
        "indented below); `key` = map key (KString+Key pair semantics per KIP-516-era",
        "encoding); `null` = nullable in this version; `tag#N` = KIP-482 tagged field",
        "N (written after the schema fields); `flexible` = KString/KArray compact",
        "encoding + tagged-field block (schema versions). Every version listed",
        "exactly matches the schema's `versions` gates — no hand curation.",
        "",
    ]
    for req, res in pairs:
        out.append(dump_one(load(req)))
        out.append(dump_one(load(res)))
    path = os.path.join(BASE, "LAYOUTS.md")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    n_sec = sum(2 * (api_max_version(load(f)) + 1) for f, _ in pairs)
    print(f"wrote {path}: {len(pairs)} API pairs, {n_sec} version sections")


if __name__ == "__main__":
    sys.exit(main())
